# Node.js Application Configuration
NODE_APP_PORT: 80
NODE_APP_SERVICE_PORT: 80
APP_REPLICAS_COUNT: 1
# MySQL Database Configuration
MYSQL_VERSION: 8.0
MYSQL_REPLICA_COUNT: 1
MYSQL_PORT: 3306
MYSQL_SERVICE_PORT: 3306

# Redis Configuration
REDIS_REPLICA_COUNT: 1
REDIS_PORT: 6379
REDIS_SERVICE_PORT: 6379